# Generated by Django 4.2.27 on 2026-01-25 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название места')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Местонахождение',
                'verbose_name_plural': 'Местонахождения',
                'db_table': 'network_location',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(default='192.168.1.0/24', max_length=18, verbose_name='Подсеть')),
                ('description', models.CharField(default='Нет описания', max_length=200, verbose_name='Описание')),
                ('vlan_id', models.IntegerField(blank=True, null=True, verbose_name='VLAN ID')),
                ('purpose', models.CharField(choices=[('client', 'Клиентская сеть'), ('server', 'Серверная сеть'), ('infrastructure', 'Сетевая инфраструктура'), ('management', 'Управление'), ('dmz', 'DMZ'), ('wireless', 'Беспроводная сеть'), ('other', 'Другое')], default='client', max_length=50, verbose_name='Назначение')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('added_by', models.CharField(default='admin', max_length=100, verbose_name='Кем добавлено')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.location')),
            ],
            options={
                'db_table': 'network_subnet',
            },
        ),
        migrations.CreateModel(
            name='NetworkEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('type', models.CharField(choices=[('router', 'Маршрутизатор'), ('switch', 'Коммутатор'), ('firewall', 'Файрвол'), ('server', 'Сервер'), ('access_point', 'Точка доступа'), ('modem', 'Модем'), ('other', 'Другое')], default='switch', max_length=20, verbose_name='Тип оборудования')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Серийный номер')),
                ('inventory_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Инвентарный номер')),
                ('rack', models.IntegerField(blank=True, null=True, verbose_name='Стойка')),
                ('unit', models.IntegerField(blank=True, null=True, verbose_name='Юнит')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IP-адрес')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC-адрес')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('backup', 'Резерв'), ('repair', 'В ремонте'), ('decommissioned', 'Списано')], default='active', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.location', verbose_name='Местонахождение')),
            ],
            options={
                'verbose_name': 'Сетевое оборудование',
                'verbose_name_plural': 'Сетевое оборудование',
                'db_table': 'network_networkequipment',
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=15, verbose_name='IP-адрес')),
                ('status', models.CharField(choices=[('free', 'Свободен'), ('reserved', 'Зарезервирован'), ('dynamic', 'DHCP'), ('occupied', 'Занят')], default='free', max_length=10, verbose_name='Статус')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC-адрес')),
                ('dns_name', models.CharField(blank=True, max_length=100, verbose_name='DNS имя')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('note', models.TextField(blank=True, verbose_name='Заметки')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.networkequipment', verbose_name='Оборудование')),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.subnet', verbose_name='Подсеть')),
            ],
            options={
                'verbose_name': 'IP-адрес',
                'verbose_name_plural': 'IP-адреса',
                'db_table': 'network_ipaddress',
                'ordering': ['address'],
            },
        ),
    ]
