# Generated by Django 4.2.27 on 2026-01-30 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_networkequipment_manufacturer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networkequipment',
            options={'ordering': ['-last_seen', 'name'], 'verbose_name': 'Сетевое оборудование', 'verbose_name_plural': 'Сетевое оборудование'},
        ),
        migrations.AddField(
            model_name='networkequipment',
            name='auto_discovered',
            field=models.BooleanField(default=False, help_text='Устройство было обнаружено сканером, а не добавлено вручную', verbose_name='Обнаружено автоматически'),
        ),
        migrations.AddField(
            model_name='networkequipment',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Когда устройство было впервые обнаружено', verbose_name='Впервые обнаружено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networkequipment',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Устройство доступно по сети', verbose_name='В сети'),
        ),
        migrations.AddField(
            model_name='networkequipment',
            name='is_temporary',
            field=models.BooleanField(default=False, help_text='Личное устройство сотрудника или временное подключение', verbose_name='Временное устройство'),
        ),
        migrations.AddField(
            model_name='networkequipment',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Когда устройство было последний раз обнаружено', null=True, verbose_name='Последний раз в сети'),
        ),
        migrations.AddField(
            model_name='networkequipment',
            name='oui_vendor',
            field=models.CharField(blank=True, help_text='Производитель, определенный по OUI MAC-адреса', max_length=200, null=True, verbose_name='Производитель (по MAC)'),
        ),
        migrations.AddField(
            model_name='networkequipment',
            name='scan_count',
            field=models.IntegerField(default=0, help_text='Сколько раз устройство было обнаружено', verbose_name='Количество сканирований'),
        ),
        migrations.AddField(
            model_name='networkequipment',
            name='scan_device_type',
            field=models.CharField(blank=True, help_text='Тип устройства, определенный сканером', max_length=50, null=True, verbose_name='Тип (определено сканером)'),
        ),
        migrations.AddField(
            model_name='networkequipment',
            name='scan_history',
            field=models.JSONField(blank=True, default=list, help_text='История обнаружений устройства', verbose_name='История сканирований'),
        ),
        migrations.AddField(
            model_name='networkequipment',
            name='scan_hostname',
            field=models.CharField(blank=True, help_text='Хостнейм, определенный сканером', max_length=100, null=True, verbose_name='Хостнейм (сканер)'),
        ),
    ]
