# Generated by Django 4.2.27 on 2026-01-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_networkequipment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networkequipment',
            options={'verbose_name': 'Сетевое оборудование', 'verbose_name_plural': 'Сетевое оборудование'},
        ),
        migrations.RemoveField(
            model_name='networkequipment',
            name='auto_discovered',
        ),
        migrations.RemoveField(
            model_name='networkequipment',
            name='first_seen',
        ),
        migrations.RemoveField(
            model_name='networkequipment',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='networkequipment',
            name='is_temporary',
        ),
        migrations.RemoveField(
            model_name='networkequipment',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='networkequipment',
            name='oui_vendor',
        ),
        migrations.RemoveField(
            model_name='networkequipment',
            name='scan_count',
        ),
        migrations.RemoveField(
            model_name='networkequipment',
            name='scan_device_type',
        ),
        migrations.RemoveField(
            model_name='networkequipment',
            name='scan_history',
        ),
        migrations.RemoveField(
            model_name='networkequipment',
            name='scan_hostname',
        ),
        migrations.AddField(
            model_name='networkequipment',
            name='scan_source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Источник обнаружения'),
        ),
    ]
