# Generated by Django 6.0 on 2026-01-19 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('issue', 'Выдача'), ('return', 'Возврат'), ('repair', 'Отправка в ремонт'), ('write_off', 'Списание')], default='issue', max_length=20, verbose_name='Действие')),
                ('date', models.DateField(verbose_name='Дата')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Кем внесено')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Сотрудник')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='equipments.equipment')),
            ],
            options={
                'verbose_name': 'История оборудования',
                'verbose_name_plural': 'История оборудования',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
