# Generated by Django 6.0 on 2025-12-30 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Дата возврата')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='equipments.equipment')),
            ],
            options={
                'verbose_name': 'История выдачи',
                'verbose_name_plural': 'История выдачи',
                'ordering': ['-issue_date'],
            },
        ),
    ]
