# Generated by Django 6.0 on 2025-12-30 16:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_email_remove_employee_phone'),
        ('equipments', '0002_equipment_assigned_to_equipment_created_at_and_more'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmenthistory',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'История оборудования', 'verbose_name_plural': 'История оборудования'},
        ),
        migrations.RemoveField(
            model_name='equipmenthistory',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='equipmenthistory',
            name='return_date',
        ),
        migrations.AddField(
            model_name='equipmenthistory',
            name='action',
            field=models.CharField(choices=[('issue', 'Выдача'), ('return', 'Возврат'), ('repair', 'Отправка в ремонт'), ('write_off', 'Списание')], default='issue', max_length=20, verbose_name='Действие'),
        ),
        migrations.AddField(
            model_name='equipmenthistory',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кем внесено'),
        ),
        migrations.AddField(
            model_name='equipmenthistory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipmenthistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='equipmenthistory',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='equipments.equipment'),
        ),
    ]
