# Generated by Django 6.0 on 2025-12-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_number', models.CharField(db_index=True, max_length=20, verbose_name='Номер МЦ')),
                ('type', models.CharField(choices=[('laptop', 'Ноутбук'), ('pc', 'Компьютер'), ('monitor', 'Монитор'), ('keyboard', 'Клавиатура'), ('mouse', 'Мышь'), ('printer', 'Принтер'), ('scanner', 'Сканер'), ('other', 'Другое')], max_length=50, verbose_name='Тип')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Марка')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('status', models.CharField(choices=[('available', 'На складе'), ('issued', 'Выдано'), ('broken', 'Сломан'), ('repair', 'В ремонте'), ('written_off', 'Списан')], default='available', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['mc_number'],
            },
        ),
    ]
