# Generated by Django 6.0 on 2026-01-19 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_number', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Номер МЦ')),
                ('type', models.CharField(choices=[('laptop', 'Ноутбук'), ('pc', 'Компьютер'), ('monitor', 'Монитор'), ('keyboard', 'Клавиатура'), ('mouse', 'Мышь'), ('printer', 'Принтер'), ('scanner', 'Сканер'), ('headphones', 'Наушники'), ('phone', 'Телефон'), ('webcam', 'Веб-камера'), ('other', 'Другое')], max_length=50, verbose_name='Тип')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Марка')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('ip_address', models.CharField(blank=True, help_text='IPv4 адрес для сетевых принтеров (например: 192.168.1.100)', max_length=15, null=True, verbose_name='IP адрес')),
                ('status', models.CharField(choices=[('available', 'На складе'), ('issued', 'Выдано'), ('broken', 'Сломан'), ('repair', 'В ремонте'), ('written_off', 'Списан')], default='issued', max_length=20, verbose_name='Статус')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='Гарантия до')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_equipment', to='employees.department', verbose_name='Закреплено за отделом')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to='employees.employee', verbose_name='Закреплено за сотрудником')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['mc_number'],
                'indexes': [models.Index(fields=['mc_number'], name='equipments__mc_numb_d7a5c8_idx'), models.Index(fields=['type'], name='equipments__type_a35dbb_idx'), models.Index(fields=['status'], name='equipments__status_df2d04_idx')],
            },
        ),
    ]
