# Generated by Django 6.0 on 2025-12-30 16:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_email_remove_employee_phone'),
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='employees.employee', verbose_name='Закреплено за'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата покупки'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='warranty_until',
            field=models.DateField(blank=True, null=True, verbose_name='Гарантия до'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('available', 'На складе'), ('issued', 'Выдано'), ('broken', 'Сломан'), ('repair', 'В ремонте'), ('written_off', 'Списан')], default='issued', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('laptop', 'Ноутбук'), ('pc', 'Компьютер'), ('monitor', 'Монитор'), ('keyboard', 'Клавиатура'), ('mouse', 'Мышь'), ('printer', 'Принтер'), ('scanner', 'Сканер'), ('headphones', 'Наушники'), ('phone', 'Стационарный телефон'), ('webcam', 'Веб-камера'), ('other', 'Другое')], max_length=50, verbose_name='Тип'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['mc_number'], name='equipments__mc_numb_d7a5c8_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['type'], name='equipments__type_a35dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status'], name='equipments__status_df2d04_idx'),
        ),
    ]
