# Generated by Django 6.0 on 2025-12-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_equipment_assigned_to_equipment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='mc_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Номер МЦ'),
        ),
    ]
