# Generated by Django 6.0 on 2025-12-31 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_alter_equipment_mc_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='serial_number',
        ),
    ]
