# Generated by Django 6.0 on 2026-01-03 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_email_remove_employee_phone'),
        ('equipments', '0004_remove_equipment_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='assigned_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_equipment', to='employees.department', verbose_name='Закреплено за отделом'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to='employees.employee', verbose_name='Закреплено за сотрудником'),
        ),
    ]
