# Generated by Django 6.0 on 2026-01-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_equipment_assigned_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('laptop', 'Ноутбук'), ('pc', 'Компьютер'), ('monitor', 'Монитор'), ('keyboard', 'Клавиатура'), ('mouse', 'Мышь'), ('printer', 'Принтер'), ('scanner', 'Сканер'), ('headphones', 'Наушники'), ('phone', 'Телефон'), ('webcam', 'Веб-камера'), ('other', 'Другое')], max_length=50, verbose_name='Тип'),
        ),
    ]
