# Generated by Django 6.0 on 2026-01-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_alter_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='ip_address',
            field=models.CharField(blank=True, help_text='IPv4 адрес для сетевых принтеров (например: 192.168.1.100)', max_length=15, null=True, verbose_name='IP адрес'),
        ),
    ]
