# Generated by Django 6.0 on 2026-01-17 20:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0007_equipment_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_online', models.BooleanField(default=False)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('printer', models.ForeignKey(limit_choices_to={'type': 'Принтер'}, on_delete=django.db.models.deletion.CASCADE, related_name='printer_checks', to='equipments.equipment')),
            ],
            options={
                'verbose_name': 'Проверка принтера',
                'verbose_name_plural': 'Проверки принтеров',
                'ordering': ['-checked_at'],
            },
        ),
    ]
