# Generated by Django 6.0 on 2026-01-19 15:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_online', models.BooleanField(default=False)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('printer', models.ForeignKey(limit_choices_to={'type': 'Принтер'}, on_delete=django.db.models.deletion.CASCADE, related_name='printer_checks', to='equipments.equipment')),
            ],
            options={
                'verbose_name': 'Проверка принтера',
                'verbose_name_plural': 'Проверки принтеров',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='PrinterCurrentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('online', 'В сети'), ('offline', 'Не в сети'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('sleep', 'Спящий режим')], default='offline', max_length=20)),
                ('black_toner_level', models.IntegerField(blank=True, null=True)),
                ('cyan_toner_level', models.IntegerField(blank=True, null=True)),
                ('magenta_toner_level', models.IntegerField(blank=True, null=True)),
                ('yellow_toner_level', models.IntegerField(blank=True, null=True)),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('has_errors', models.BooleanField(default=False)),
                ('has_warnings', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True)),
                ('uptime_24h', models.FloatField(default=0.0)),
                ('last_successful_check', models.DateTimeField(blank=True, null=True)),
                ('printer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_status', to='equipments.equipment')),
            ],
            options={
                'verbose_name': 'Текущий статус',
                'verbose_name_plural': 'Текущие статусы',
            },
        ),
        migrations.CreateModel(
            name='PrinterDetailCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('online', 'В сети'), ('offline', 'Не в сети'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('sleep', 'Спящий режим')], max_length=20)),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('color_pages', models.IntegerField(blank=True, null=True)),
                ('monochrome_pages', models.IntegerField(blank=True, null=True)),
                ('black_toner', models.IntegerField(blank=True, null=True)),
                ('cyan_toner', models.IntegerField(blank=True, null=True)),
                ('magenta_toner', models.IntegerField(blank=True, null=True)),
                ('yellow_toner', models.IntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('check_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_checks', to='equipments.equipment')),
            ],
            options={
                'verbose_name': 'Детальная проверка',
                'verbose_name_plural': 'Детальные проверки',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='PrinterStatusCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_online', models.BooleanField(default=False)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('ping_success', models.BooleanField(default=False)),
                ('http_success', models.BooleanField(default=False)),
                ('snmp_success', models.BooleanField(default=False)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_checks', to='equipments.equipment')),
            ],
            options={
                'verbose_name': 'Быстрая проверка',
                'verbose_name_plural': 'Быстрые проверки',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['printer', '-checked_at'], name='printer_mon_printer_9bd518_idx'), models.Index(fields=['checked_at'], name='printer_mon_checked_075a75_idx')],
            },
        ),
    ]
