# Generated by Django 4.2.27 on 2026-01-21 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
        ('printer_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printerdetailcheck',
            name='printer',
        ),
        migrations.RemoveField(
            model_name='printerstatuscheck',
            name='printer',
        ),
        migrations.AlterField(
            model_name='printercheck',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printercheck',
            name='printer',
            field=models.ForeignKey(limit_choices_to={'type': 'printer'}, on_delete=django.db.models.deletion.CASCADE, related_name='printer_checks', to='equipments.equipment'),
        ),
        migrations.AddIndex(
            model_name='printercheck',
            index=models.Index(fields=['printer', '-checked_at'], name='printer_mon_printer_17c587_idx'),
        ),
        migrations.AddIndex(
            model_name='printercheck',
            index=models.Index(fields=['checked_at'], name='printer_mon_checked_1beb17_idx'),
        ),
        migrations.AddIndex(
            model_name='printercheck',
            index=models.Index(fields=['is_online'], name='printer_mon_is_onli_766204_idx'),
        ),
        migrations.AddIndex(
            model_name='printercurrentstatus',
            index=models.Index(fields=['is_online'], name='printer_mon_is_onli_c5b8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='printercurrentstatus',
            index=models.Index(fields=['last_updated'], name='printer_mon_last_up_283e02_idx'),
        ),
        migrations.DeleteModel(
            name='PrinterDetailCheck',
        ),
        migrations.DeleteModel(
            name='PrinterStatusCheck',
        ),
    ]
