# Generated by Django 4.2.27 on 2026-01-21 08:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
        ('printer_monitor', '0002_remove_printerdetailcheck_printer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pages_count', models.IntegerField(blank=True, null=True)),
                ('toner_level', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipment')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PrinterAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=255)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
