# Generated by Django 4.2.27 on 2026-01-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer_monitor', '0003_printermetric_printeralert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printeralert',
            name='printer',
        ),
        migrations.RemoveField(
            model_name='printermetric',
            name='printer',
        ),
        migrations.AlterModelOptions(
            name='printercheck',
            options={'ordering': ['-checked_at']},
        ),
        migrations.RemoveIndex(
            model_name='printercheck',
            name='printer_mon_printer_17c587_idx',
        ),
        migrations.RemoveIndex(
            model_name='printercheck',
            name='printer_mon_checked_1beb17_idx',
        ),
        migrations.RemoveIndex(
            model_name='printercheck',
            name='printer_mon_is_onli_766204_idx',
        ),
        migrations.RemoveIndex(
            model_name='printercurrentstatus',
            name='printer_mon_is_onli_c5b8ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='printercurrentstatus',
            name='printer_mon_last_up_283e02_idx',
        ),
        migrations.RemoveField(
            model_name='printercurrentstatus',
            name='black_toner_level',
        ),
        migrations.RemoveField(
            model_name='printercurrentstatus',
            name='cyan_toner_level',
        ),
        migrations.RemoveField(
            model_name='printercurrentstatus',
            name='has_errors',
        ),
        migrations.RemoveField(
            model_name='printercurrentstatus',
            name='has_warnings',
        ),
        migrations.RemoveField(
            model_name='printercurrentstatus',
            name='last_error',
        ),
        migrations.RemoveField(
            model_name='printercurrentstatus',
            name='last_successful_check',
        ),
        migrations.RemoveField(
            model_name='printercurrentstatus',
            name='magenta_toner_level',
        ),
        migrations.RemoveField(
            model_name='printercurrentstatus',
            name='total_pages',
        ),
        migrations.RemoveField(
            model_name='printercurrentstatus',
            name='uptime_24h',
        ),
        migrations.RemoveField(
            model_name='printercurrentstatus',
            name='yellow_toner_level',
        ),
        migrations.AlterField(
            model_name='printercurrentstatus',
            name='status',
            field=models.CharField(choices=[('online', 'В сети'), ('offline', 'Не в сети')], default='offline', max_length=20),
        ),
        migrations.DeleteModel(
            name='PrinterAlert',
        ),
        migrations.DeleteModel(
            name='PrinterMetric',
        ),
    ]
